/* This is created by executing ./generate_album_lists.sh ThisYear */
window.BETHEL_ALBUM_FILES = [
  "./album/ThisYear/2nd-Watermelon-Day/1.jpg",
  "./album/ThisYear/2nd-Watermelon-Day/2.jpg",
  "./album/ThisYear/2nd-Watermelon-Day/3.jpg",
  "./album/ThisYear/2nd-Watermelon-Day/cover.png",
  "./album/ThisYear/Mrs. Oh's 80th Birthday/1.jpg",
  "./album/ThisYear/Mrs. Oh's 80th Birthday/2.jpg",
  "./album/ThisYear/Mrs. Oh's 80th Birthday/cover.png",
  "./album/ThisYear/Sunday-EM-Worship/1.jpg",
  "./album/ThisYear/Sunday-EM-Worship/1.mp4",
  "./album/ThisYear/Sunday-EM-Worship/2.jpg",
  "./album/ThisYear/Sunday-EM-Worship/3.jpg",
  "./album/ThisYear/Sunday-EM-Worship/5.jpg",
  "./album/ThisYear/Sunday-EM-Worship/6.jpg",
  "./album/ThisYear/Sunday-EM-Worship/cover.png",
  "./album/ThisYear/Youth Group Beach Retreat/2.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/1.mp4",
  "./album/ThisYear/Youth Group Beach Retreat/2.mp4",
  "./album/ThisYear/Youth Group Beach Retreat/3.mp4",
  "./album/ThisYear/Youth Group Beach Retreat/3.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/4.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/5.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/6.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/7.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/8.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/9.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/10.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/11.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/12.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/13.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/14.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/15.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/16.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/17.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/18.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/19.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/20.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/21.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/22.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/23.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/24.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/25.jpg",
  "./album/ThisYear/Youth Group Beach Retreat/cover.png"
];
